# Generated by Django 3.1.1 on 2020-09-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_posted_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post',
            field=models.TextField(default='No post yet'),
        ),
        migrations.AddField(
            model_name='posts',
            name='posted_on_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Published date'),
        ),
    ]
