# Generated by Django 3.1.1 on 2020-09-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0003_auto_20200914_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posted_on_date',
            new_name='posted_on',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AddField(
            model_name='posts',
            name='author_id',
            field=models.ForeignKey(blank=True, default='202009141247453969240000', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='post_id',
            field=models.AutoField(default=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
