# Generated by Django 3.1.1 on 2020-09-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='DateTime when account was made.')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
